const decorationsList = [
  {
    id: 0,
    name: "boule1",
    url: "./images/boule1.png",
    type: "boule",
  },
  {
    id: 1,
    name: "boule2",
    url: "./images/boule2.png",
    type: "boule",
  },
  {
    id: 2,
    name: "deco1",
    url: "./images/deco1.webp",
    type: "extra",
  },
  {
    id: 3,
    name: "boule3",
    url: "./images/boule3.png",
    type: "boule",
  },
  {
    id: 4,
    name: "boule4",
    url: "./images/boule4.png",
    type: "boule",
  },
  {
    id: 5,
    name: "star1",
    url: "./images/star1.png",
    type: "star",
  },
  {
    id: 6,
    name: "boule5",
    url: "./images/boule5.png",
    type: "boule",
  },
  {
    id: 7,
    name: "boule6",
    url: "./images/boule6.png",
    type: "boule",
  },
  {
    id: 8,
    name: "deco2",
    url: "./images/deco2.png",
    type: "extra",
  },
  // {
  //     id:9,
  //     name:"boule7",
  //     url:"./images/boule7.png",
  //     type:"boule",
  // },
  // {
  //     id:10,
  //     name:"boule8",
  //     url:"./images/boule8.png",
  //     type:"boule",
  // },
  // {
  //     id:11,
  //     name:"star2",
  //     url:"./images/star2.png",
  //     type:"star",
  // },
  {
    id: 12,
    name: "boule9",
    url: "./images/boule9.png",
    type: "boule",
  },
  // {
  //     id:13,
  //     name:"boule10",
  //     url:"./images/boule10.png",
  //     type:"boule",
  // },
  {
    id: 14,
    name: "deco3",
    url: "./images/deco3.png",
    type: "extra",
  },
  {
    id: 15,
    name: "boule11",
    url: "./images/boule11.png",
    type: "boule",
  },
  {
    id: 16,
    name: "boule12",
    url: "./images/boule12.png",
    type: "boule",
  },
  {
    id: 17,
    name: "star3",
    url: "./images/star2.png",
    type: "star",
  },
  {
    id: 18,
    name: "boule13",
    url: "./images/boule13.png",
    type: "boule",
  },
  {
    id: 19,
    name: "boule14",
    url: "./images/boule14.png",
    type: "boule",
  },
  {
    id: 20,
    name: "deco4",
    url: "./images/deco4.png",
    type: "extra",
  },
  // {
  //     id:21,
  //     name:"boule15",
  //     url:"./images/boule15.png",
  //     type:"boule",
  // },
  {
    id: 22,
    name: "boule16",
    url: "./images/boule16.png",
    type: "boule",
  },
  {
    id: 23,
    name: "star4",
    url: "./images/star4.png",
    type: "star",
  },
  {
    id: 24,
    name: "boule17",
    url: "./images/boule17.png",
    type: "boule",
  },
  {
    id: 25,
    name: "boule18",
    url: "./images/boule18.png",
    type: "boule",
  },
  {
    id: 26,
    name: "deco5",
    url: "./images/deco5.png",
    type: "extra",
  },
  {
    id: 27,
    name: "boule19",
    url: "./images/boule19.png",
    type: "boule",
  },
  {
    id: 28,
    name: "boule20",
    url: "./images/boule20.png",
    type: "boule",
  },
  {
    id: 29,
    name: "deco6",
    url: "./images/deco6.png",
    type: "extra",
  },
  {
    id: 30,
    name: "boule21",
    url: "./images/boule21.png",
    type: "boule",
  },
  {
    id: 31,
    name: "boule22",
    url: "./images/boule22.png",
    type: "boule",
  },
  {
    id: 32,
    name: "deco7",
    url: "./images/deco7.png",
    type: "extra",
  },
  {
    id: 33,
    name: "boule23",
    url: "./images/deco7.png",
    type: "boule",
  },
  {
    id: 34,
    name: "boule24",
    url: "./images/boule24.png",
    type: "boule",
  },
  {
    id: 35,
    name: "boule25",
    url: "./images/boule25.png",
    type: "boule",
  },
  {
    id: 36,
    name: "boule26",
    url: "./images/boule26.png",
    type: "boule",
  },
  {
    id: 37,
    name: "boule27",
    url: "./images/boule27.png",
    type: "boule",
  },
];

export default decorationsList;
